"use client";

import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { TwinShell } from "@/features/os/shell/twin-shell";
import {
  fetchInventory,
  mutateInventory,
  InventoryClientError,
} from "@/features/os/operational/adapters/inventory-client";
import {
  OperationalTable,
  type OperationalTableColumn,
} from "@/features/os/operational/components/operational-ui";
import { displayCell } from "@/lib/inventory/calcs";
import type { MeAlert, MeMaterial } from "@/lib/inventory/types";
import { canWriteInventory } from "@/lib/inventory/rbac";
import { usePreviewSession } from "@/features/os/session/preview-context";
import { pushNotification } from "@/features/os/feedback/notifications-store";
import { ME_ALERT_NOTIFY_SECTORS } from "@/lib/inventory/rbac";

export function MeAvisosView() {
  const { sectorId } = usePreviewSession();
  const canWrite = canWriteInventory(sectorId, "me_avisos");
  const isDeposito = sectorId === "DEPOSITO";
  const [alerts, setAlerts] = useState<MeAlert[]>([]);
  const [materials, setMaterials] = useState<MeMaterial[]>([]);
  const [banner, setBanner] = useState<string | null>(null);
  const [materialId, setMaterialId] = useState("");
  const [obs, setObs] = useState("");

  const reload = useCallback(async () => {
    const [a, m] = await Promise.all([
      fetchInventory<MeAlert>("me_avisos"),
      fetchInventory<MeMaterial>("me_stock"),
    ]);
    setAlerts(a.data);
    setMaterials(m.data);
    setBanner(a.message ?? null);
  }, []);

  useEffect(() => {
    let cancelled = false;
    queueMicrotask(() => {
      void (async () => {
        try {
          await reload();
        } catch (e) {
          if (!cancelled) setBanner(e instanceof Error ? e.message : "Error");
        }
      })();
    });
    return () => {
      cancelled = true;
    };
  }, [reload]);

  const columns: OperationalTableColumn<MeAlert>[] = [
    { key: "material", header: "Material", render: (r) => displayCell(r.materialDescripcion) },
    { key: "codigo", header: "Código", render: (r) => displayCell(r.codigo) },
    { key: "stock", header: "Stock actual", render: (r) => displayCell(r.stockActual) },
    { key: "min", header: "Stock mínimo", render: (r) => displayCell(r.stockMinimo) },
    {
      key: "sugerida",
      header: "Cant. sugerida",
      render: (r) => displayCell(r.cantidadSugerida),
    },
    { key: "ubicacion", header: "Ubicación", render: (r) => displayCell(r.ubicacion) },
    { key: "fecha", header: "Fecha", render: (r) => displayCell(r.createdAt.slice(0, 10)) },
    { key: "estado", header: "Estado", render: (r) => r.status },
    {
      key: "origen",
      header: "Origen",
      render: (r) => (r.autoGenerated ? "Automático" : "Manual"),
    },
    { key: "obs", header: "Observaciones", render: (r) => displayCell(r.observaciones) },
    {
      key: "acciones",
      header: "",
      render: (r) =>
        canWrite ? (
          <div className="flex flex-wrap gap-1">
            <Button
              type="button"
              size="sm"
              variant="secondary"
              onClick={() =>
                void mutateInventory({
                  action: "patch",
                  resource: "me_avisos",
                  id: r.id,
                  payload: { status: "COMPRA_SOLICITADA" },
                }).then(reload)
              }
            >
              Compra solicitada
            </Button>
            <Button
              type="button"
              size="sm"
              variant="secondary"
              onClick={() =>
                void mutateInventory({
                  action: "patch",
                  resource: "me_avisos",
                  id: r.id,
                  payload: { status: "RESUELTO" },
                }).then(reload)
              }
            >
              Resuelto
            </Button>
            {isDeposito && (
              <Button
                type="button"
                size="sm"
                variant="secondary"
                onClick={() =>
                  void mutateInventory({
                    action: "patch",
                    resource: "me_avisos",
                    id: r.id,
                    payload: { status: "ARCHIVADO" },
                  }).then(reload)
                }
              >
                Archivar
              </Button>
            )}
          </div>
        ) : null,
    },
  ];

  return (
    <TwinShell title="Avisos">
      {banner && (
        <div className="mb-4 rounded border border-amber-300 bg-amber-50 px-3 py-2 text-sm">{banner}</div>
      )}
      {isDeposito && (
        <div className="mb-4 flex flex-wrap items-end gap-2 rounded border p-3">
          <label className="text-sm">
            Material
            <select
              className="mt-1 block rounded border px-2 py-1"
              value={materialId}
              onChange={(e) => setMaterialId(e.target.value)}
            >
              <option value="">—</option>
              {materials.map((m) => (
                <option key={m.id} value={m.id}>
                  {m.descripcion}
                </option>
              ))}
            </select>
          </label>
          <label className="text-sm">
            Observación
            <input
              className="mt-1 block rounded border px-2 py-1"
              value={obs}
              onChange={(e) => setObs(e.target.value)}
            />
          </label>
          <Button
            type="button"
            onClick={() => {
              if (!materialId) return;
              void mutateInventory<MeAlert>({
                action: "create",
                resource: "me_avisos",
                payload: { materialId, observaciones: obs },
              })
                .then((res) => {
                  const a = res.data;
                  pushNotification({
                    kind: "me_aviso",
                    title: `Stock bajo de ${a.materialDescripcion}`,
                    message: `Quedan ${a.stockActual} unidades.${
                      a.stockMinimo != null
                        ? ` El stock mínimo configurado es ${a.stockMinimo}.`
                        : ""
                    }${
                      a.cantidadSugerida != null
                        ? ` Depósito recomienda comprar ${a.cantidadSugerida}.`
                        : ""
                    }`,
                    sectors: ME_ALERT_NOTIFY_SECTORS,
                  });
                  return reload();
                })
                .catch((e) =>
                  setBanner(e instanceof InventoryClientError ? e.message : "Error")
                );
            }}
          >
            Crear aviso manual
          </Button>
        </div>
      )}
      <OperationalTable
        columns={columns}
        rows={alerts}
        rowKey={(r) => r.id}
        emptyMessage="Sin avisos. Se generan al cruzar umbrales de stock ME."
      />
    </TwinShell>
  );
}
