import { describe, expect, it } from "vitest";
import { applySort } from "@/lib/sorting/sort-contract";
import type { MeAlert, MeInventarioViewRow, MeIngresoRow, MeSalidaRow } from "@/lib/inventory/types";
import { ME_INGRESO_SORT_OPTIONS } from "./me-ingresos-view";
import { ME_SALIDA_SORT_OPTIONS } from "./me-salidas-view";
import { ME_INVENTARIO_SORT_OPTIONS } from "./me-inventario-view";
import { ME_AVISOS_SORT_OPTIONS } from "./me-avisos-view";

/**
 * AUDIT_ORDENAMIENTO_GLOBAL — ninguna de las 4 pantallas de Material de
 * Empaque (Ingresos/Salidas/Inventario/Avisos) tenía ordenamiento
 * seleccionable: Ingresos/Salidas/Avisos no tenían NADA, e Inventario tenía
 * un orden fijo por código (server-side, no elegible). Un test por
 * pantalla contra los comparadores reales exportados.
 */
function ingreso(overrides: Partial<MeIngresoRow>): MeIngresoRow {
  return {
    id: overrides.id ?? "id",
    fecha: "2026-08-03",
    ingresoNro: "1",
    proveedor: "",
    cliente: "",
    remitoNro: "",
    codigo: "C",
    descripcionInsumo: "",
    bultos: null,
    cantidad: null,
    total: null,
    ubicacion: "",
    ...overrides,
  } as MeIngresoRow;
}

function salida(overrides: Partial<MeSalidaRow>): MeSalidaRow {
  return {
    id: overrides.id ?? "id",
    fecha: "2026-08-03",
    egresoNro: "1",
    cliente: "",
    remitoNro: "",
    descripcion: "",
    bultos: null,
    cantidad: null,
    total: null,
    control: false,
    entregado: false,
    comentarios: "",
    materialId: null,
    codigo: "C",
    unidad: "",
    origen: "MANUAL",
    oaId: null,
    oaNumber: null,
    oaVersion: null,
    materialLineId: null,
    idempotencyKey: null,
    reverted: false,
    ...overrides,
  } as MeSalidaRow;
}

function inventarioRow(overrides: Partial<MeInventarioViewRow>): MeInventarioViewRow {
  return {
    materialId: overrides.materialId ?? "id",
    codigo: "C",
    cliente: "",
    insumo: "",
    bultosDisplay: "",
    cantidadTotal: 0,
    ubicacion: "",
    updatedAt: "2026-08-03T12:00:00.000Z",
    ...overrides,
  };
}

function aviso(overrides: Partial<MeAlert>): MeAlert {
  return {
    id: overrides.id ?? "id",
    materialId: "m1",
    materialDescripcion: "Material",
    codigo: "C",
    stockActual: 0,
    stockMinimo: null,
    cantidadSugerida: null,
    ubicacion: "",
    status: "STOCK_BAJO",
    autoGenerated: true,
    observaciones: "",
    createdAt: "2026-08-03T12:00:00.000Z",
    updatedAt: "2026-08-03T12:00:00.000Z",
    resolvedAt: null,
    ...overrides,
  };
}

describe("me-ingresos-view — ME_INGRESO_SORT_OPTIONS", () => {
  it("fecha_desc y total_asc funcionan (numérico)", () => {
    const rows = [
      ingreso({ id: "a", fecha: "2026-08-10", total: 100 }),
      ingreso({ id: "b", fecha: "2026-01-01", total: 9 }),
    ];
    expect(applySort(rows, ME_INGRESO_SORT_OPTIONS, "fecha_desc").map((r) => r.id)).toEqual(["a", "b"]);
    expect(applySort(rows, ME_INGRESO_SORT_OPTIONS, "total_asc").map((r) => r.total)).toEqual([9, 100]);
  });
});

describe("me-salidas-view — ME_SALIDA_SORT_OPTIONS", () => {
  it("fecha_desc y codigo_asc funcionan", () => {
    const rows = [
      salida({ id: "a", fecha: "2026-08-10", codigo: "Z" }),
      salida({ id: "b", fecha: "2026-01-01", codigo: "A" }),
    ];
    expect(applySort(rows, ME_SALIDA_SORT_OPTIONS, "fecha_desc").map((r) => r.id)).toEqual(["a", "b"]);
    expect(applySort(rows, ME_SALIDA_SORT_OPTIONS, "codigo_asc").map((r) => r.id)).toEqual(["b", "a"]);
  });
});

describe("me-inventario-view — ME_INVENTARIO_SORT_OPTIONS", () => {
  it("cantidad_desc/asc son numéricas (antes: solo fixed código A-Z, sin control)", () => {
    const rows = [
      inventarioRow({ materialId: "a", cantidadTotal: 100 }),
      inventarioRow({ materialId: "b", cantidadTotal: 9 }),
    ];
    expect(applySort(rows, ME_INVENTARIO_SORT_OPTIONS, "cantidad_asc").map((r) => r.cantidadTotal)).toEqual([
      9, 100,
    ]);
  });
});

describe("me-avisos-view — ME_AVISOS_SORT_OPTIONS", () => {
  it("stock_asc ordena numéricamente (antes: sin ningún orden)", () => {
    const rows = [aviso({ id: "a", stockActual: 100 }), aviso({ id: "b", stockActual: 9 })];
    expect(applySort(rows, ME_AVISOS_SORT_OPTIONS, "stock_asc").map((r) => r.stockActual)).toEqual([9, 100]);
  });
});
