/** Tipos de dominio inventario ME / MP (Neon). */

export type MeIngresoRow = {
  id: string;
  fecha: string;
  ingresoNro: string;
  proveedor: string;
  cliente: string;
  remitoNro: string;
  codigo: string;
  descripcionInsumo: string;
  bultos: number | null;
  cantidad: number | null;
  /** TOTAL = BULTOS × CANTIDAD (unidades). */
  total: number | null;
  ubicacion: string;
  materialId: string | null;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
};

export type MeSalidaOrigen = "MANUAL" | "OA";

export type MeSalidaRow = {
  id: string;
  fecha: string;
  egresoNro: string;
  cliente: string;
  remitoNro: string;
  descripcion: string;
  bultos: number | null;
  cantidad: number | null;
  total: number | null;
  control: boolean;
  entregado: boolean;
  comentarios: string;
  materialId: string | null;
  /** Código funcional del material (clave de conciliación). */
  codigo: string;
  unidad: string;
  /** Solo salidas con origen OA descuentan inventario. */
  origen: MeSalidaOrigen;
  oaId: string | null;
  oaNumber: string | null;
  oaVersion: number | null;
  materialLineId: string | null;
  /** oaId + oaVersion + materialLineId */
  idempotencyKey: string | null;
  reverted: boolean;
  revertedAt: string | null;
  revertReason: string | null;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
};

export type MeMaterial = {
  id: string;
  /** Código funcional único por material (no UUID). */
  codigo: string;
  descripcion: string;
  cliente: string;
  ubicacion: string;
  unidad: string;
  /** Unidades por bulto cerrado; null = no calcular bultos. */
  cantidadPorBulto: number | null;
  /** STOCK = ingresos − salidas OA (recalculado). */
  stockActual: number;
  stockMinimo: number | null;
  puntoReposicion: number | null;
  responsable: string;
  observacion: string;
  updatedAt: string;
};

/** Fila visible de Inventario ME (5 columnas). */
export type MeInventarioViewRow = {
  materialId: string;
  codigo: string;
  cliente: string;
  insumo: string;
  bultosDisplay: string;
  cantidadTotal: number;
  ubicacion: string;
  updatedAt: string;
};

export const ME_INVENTARIO_COLUMNS = [
  "CLIENTE",
  "INSUMO",
  "BULTOS",
  "CANTIDAD TOTAL",
  "UBICACIÓN",
] as const;

export type MeAlertStatus =
  | "STOCK_OK"
  | "STOCK_BAJO"
  | "STOCK_CRITICO"
  | "SIN_STOCK"
  | "COMPRA_SOLICITADA"
  | "RESUELTO"
  | "STOCK_RECUPERADO"
  | "ARCHIVADO";

export type MeAlert = {
  id: string;
  materialId: string;
  materialDescripcion: string;
  codigo: string;
  stockActual: number;
  stockMinimo: number | null;
  cantidadSugerida: number | null;
  ubicacion: string;
  status: MeAlertStatus;
  autoGenerated: boolean;
  observaciones: string;
  createdAt: string;
  updatedAt: string;
  resolvedAt: string | null;
};

export type MeAlertRead = {
  alertId: string;
  actorEmail: string;
  readAt: string;
  dismissedAt: string | null;
};

export type MpStockRow = {
  id: string;
  proveedor: string;
  cliente: string;
  descripcion: string;
  cantidadKg: number | null;
  ubicacion: string;
  lote: string;
  vencimiento: string;
  estadoStock: string;
  diasAlVence: number | null;
  estadoVencimiento: string;
  origen: string;
  codigo: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
};

export type MpIngresoRow = {
  id: string;
  fecha: string;
  ingresoNro: string;
  proveedor: string;
  cliente: string;
  remitoNro: string;
  codigo: string;
  descripcion: string;
  bultos: number | null;
  cantidad: number | null;
  total: number | null;
  ubicacion: string;
  lote: string;
  vencimiento: string;
  stockLotId: string | null;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
};

export type MpControlRow = {
  id: string;
  semanaLabel: string;
  productoElaborar: string;
  materiaPrima: string;
  cantNecesaria: number | null;
  enInventario: number | null;
  falta: number | null;
  estado: string;
  observacion: string;
  inventarioOrigen: "STOCK" | "MANUAL" | "";
  stockLotId: string | null;
  archived: boolean;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
};

export type MpCompraEstado =
  | ""
  | "Pendiente de definir"
  | "Solicitada"
  | "Cotizando"
  | "Comprada"
  | "En camino"
  | "Entrega demorada"
  | "En planta"
  | "Aporta cliente"
  | "Cancelada";

export type MpCompraRow = {
  id: string;
  fecha: string;
  materiaPrima: string;
  cantidad: number | null;
  unidad: string;
  proveedor: string;
  fechaEntrega: string;
  produccionesAfecta: string;
  estado: MpCompraEstado | string;
  nota: string;
  linkedIngresoId: string | null;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
};

export type InventoryAudit = {
  id: string;
  module: string;
  entityId: string;
  action: string;
  actor: string;
  actorSector: string;
  reason: string | null;
  before: Record<string, unknown> | null;
  after: Record<string, unknown> | null;
  createdAt: string;
};

export const ME_INGRESO_COLUMNS = [
  "FECHA",
  "INGRESO Nº",
  "PROVEEDOR",
  "CLIENTE",
  "REMITO Nº",
  "CÓDIGO",
  "DESCRIPCIÓN INSUMO",
  "BULTOS",
  "CANTIDAD",
  "TOTAL",
  "UBICACIÓN",
] as const;

export const ME_SALIDA_COLUMNS = [
  "FECHA",
  "EGRESO N.º",
  "CLIENTE",
  "REMITO N.º",
  "DESCRIPCIÓN",
  "BULTOS",
  "CANTIDAD",
  "TOTAL",
  "CONTROL",
  "ENTREGADO",
  "COMENTARIOS",
] as const;

export const MP_STOCK_COLUMNS = [
  "PROVEEDOR",
  "CLIENTE",
  "DESCRIPCIÓN MATERIA PRIMA",
  "CANTIDAD (KG)",
  "UBICACIÓN",
  "LOTE",
  "VENCIMIENTO",
  "ESTADO STOCK",
  "DÍAS AL VENCE",
  "ESTADO VENCIMIENTO",
  "ORIGEN",
] as const;

export const MP_INGRESO_COLUMNS = [
  "FECHA",
  "INGRESO Nº",
  "PROVEEDOR",
  "CLIENTE",
  "REMITO Nº",
  "CÓDIGO",
  "DESCRIPCIÓN MATERIA PRIMA",
  "BULTOS",
  "CANTIDAD (kg/u)",
  "TOTAL",
  "UBICACIÓN",
  "LOTE",
  "VENCIMIENTO",
] as const;

export const MP_CONTROL_COLUMNS = [
  "PRODUCTO A ELABORAR",
  "MATERIA PRIMA",
  "CANT. NECESARIA",
  "EN INVENTARIO",
  "FALTA",
  "ESTADO",
  "OBSERVACIÓN",
] as const;

export const MP_COMPRA_COLUMNS = [
  "FECHA",
  "MATERIA PRIMA",
  "CANTIDAD",
  "UNIDAD",
  "PROVEEDOR",
  "FECHA ENTREGA",
  "QUÉ PRODUCCIONES AFECTA",
  "ESTADO",
  "NOTA",
] as const;

export const MP_TABS = ["Stock", "Ingresos MP", "Control semanal", "Compras MP"] as const;
